name = "Pride MC"
author = "Saragon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f23110bce3728f7966f14d5de1307518a1db9043eb73604c85a46b0491fe691"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
