name = "Pride MC"
author = "Saragon"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5ad609375eaa2982dd303b12c7e2805056af489fc6b014e2a4bbbc1f307f6be"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
