name = "Pride MC"
author = "Saragon"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02a19aef685c77948ac58cffb3f7fe77f2b46db65eca9954e4d7f46f1a146014"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
