name = "Pride MC"
author = "Saragon"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3314b15ff641e8f7b2dc9e1849f5bfa32a6ef3f1895bfe4d8138d4b8f07b7117"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
