name = "Pride MC"
author = "Saragon"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d6aab5be0718b21cca75ff80c438db7934f26437ac553bc4b480c7f9f076694"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
