name = "Pride MC"
author = "Saragon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61295e7d28019faad79177e7e45712b6b18527fcb8e359bc933a5f07fed6a63a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
